kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: registry-puller-route
  labels:
    app: registry-puller
spec:
  to:
    kind: Service
    name: registry-puller-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
