kind: Service
apiVersion: v1
metadata:
  namespace: {{ocp-namespace}}
  name: registry-puller-service
  labels:
    app: registry-puller
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: registry-puller